config/routes.rb
Rails.application.routes.draw do
  resources :reservations, except: [:index, :show]
  resources :rooms, only: [:index, :show]

  root 'rooms#index'

end

app/models/activity_type.rb
class ActivityType < ActiveRecord::Base
  has_many :reservations
  validates :name, presence: true
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :room
  belongs_to :activity_type

  validates_associated :room
  validates_associated :activity_type

  validates :room, presence: true
  validates :activity_type, presence: true
  validates :username, presence: true

  validate :time_period

  scope :today_reservations, -> { where(active: true, start: Time.now.beginning_of_day..(Time.now.end_of_day)) }

  protected
  def time_period
    errors.add(:start, 'can\'t be blank') if start.blank?
    errors.add(:finish, 'can\'t be blank') if finish.blank?
    return if start.nil? || finish.nil?

    if(start >= finish)
      errors.add(:start, 'should be earlier than finish')
      errors.add(:finish, 'should be later than start')
      return
    end

    today_for_this_room = Reservation.today_reservations.where(room: room).where.not(id: id)

    fail = false
    today_for_this_room.each do |existing_reservation|
      if(start >= existing_reservation.start && start < existing_reservation.finish)
        errors.add(:start, 'is in existing reservation')
        fail = true
      end

      if(finish > existing_reservation.start && finish <= existing_reservation.finish)
        errors.add(:finish, 'is in existing reservation')
        fail = true
      end
      return if fail

      if(existing_reservation.start >= start && existing_reservation.start < finish)
        errors.add(:start, 'Existing reservation is in time range')
        errors.add(:finish, 'Existing reservation is in time range')
        return
      end
    end
  end

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :reservations
  validates :name, presence: true
  has_many :today_reservations, -> { where(active: true, start: Time.now.beginning_of_day..(Time.now.end_of_day)) }, class_name: 'Reservation'

  # statuses: free, busy, nearly_free, nearly_busy
  def reservation_status
    now_time = Time.now

    today_reserved = reservations.where(active: true).where("finish > ?", now_time).order(:start)
    return :free if today_reserved.blank?

    if today_reserved.first.start <= now_time
      if (today_reserved.first.finish - now_time) >= 15.minutes
        return :busy
      else
        if today_reserved.second.nil? || (today_reserved.second.start - now_time) > 30.minutes
          return :nearly_free
        else
          return :busy
        end
      end
    else
      if (today_reserved.first.start - now_time) >= 15.minutes
        return :free
      else
        return :nearly_busy
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :all_room, :activity_type, only: [:new, :create, :update]


  private
    def all_room
      @room ||= Room.all
    end

    def activity_type
      @activity_type ||= ActivityType.all
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    start = Time.now.midnight + params[:start].to_i.minutes
    @reservation = Reservation.new({room_id: params[:room_id], start: start, finish: start + 30.minutes, secretword: cookies[:secretword]})
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        cookies[:secretword] = @reservation.secretword unless @reservation.secretword.blank?
        format.html { redirect_to room_path(@reservation[:room_id]), notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    if @reservation.secretword.present? && @reservation.secretword != cookies[:secretword]
      if @reservation.secretword != params[:secretword]
        flash[:danger] = 'Secret word is wrong.' if params[:secretword].present?
        render('_form_secretword') && return
      end
    end
    @reservation.update_attributes(active: false)
    respond_to do |format|
      format.html { redirect_to room_path(@reservation.room), notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:room_id, :start, :finish, :activity_type_id, :username, :secretword, :comment, :active)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @reservations = @room.today_reservations
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_alerts.html.haml
- flash.each do |name, msg|
  .alert{ class: "alert-#{name}", role: 'alert' }
    %strong= "#{name.capitalize}!"
    = msg
    = link_to '&times;'.html_safe, '#', class: 'close'

app/views/layouts/_main_menu.html.haml
.menu_header
  .pull-left{style: "margin-left: 10px; margin-top: 2px;"}
    .logo= link_to(image_tag('logo.png'), root_path)
  .pull-right.dropdown
    .status-help.glyphicon.glyphicon-align-justify.pull-right{"data-toggle" => "dropdown", style:"margin-right:20px"}
    %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1"}
      %li{style: "padding-top: 7px;"}
        .free.pull-left.pr50mr20free
        = "&nbsp;".html_safe
        Free
      %li.divider
      %li
        .busy.pull-left.pr50mr20
        = "&nbsp;".html_safe
        Busy
      %li.divider
      %li
        .nearly_busy.pull-left.pr50mr20
        = "&nbsp;".html_safe
        Will be busy on 15 min.
      %li.divider
      %li
        .nearly_free.pull-left.pr50mr20nearly_free
        = "&nbsp;".html_safe
        Will be free on 15 min.
  .clearfix

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: 'utf-8'}
    %title ComfortConference
    %meta{content: 'width=device-width, initial-scale=1.0', name: 'viewport'}
    %meta{content: '', name: 'description'}
    %meta{content: '', name: 'author'}
    %link{rel: 'stylesheet', type: 'text/css', href: 'http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin'}

    = stylesheet_link_tag    :application, media: :all
    = csrf_meta_tags
  %body{class: "#{controller.controller_name}_#{controller.action_name} #{controller.controller_name}_controller"}
    = render 'layouts/main_menu'
    = yield

    = javascript_include_tag :application, media: :all

app/views/reservations/_form.html.haml
- room_id = params[:reservation].blank? ? params[:room_id] : params[:reservation][:room_id]
- room = Room.find(room_id)
.col-md-6.col-lg-6
  = simple_form_for @reservation, role: 'form' do |f|
    - if @reservation.errors.any?
      #error_explanation
        %h2= "#{pluralize(@reservation.errors.count, "error")} prohibited this reservation from being saved:"
        %ul
          - @reservation.errors.full_messages.each do |msg|
            %li= msg

    .form-group.form-group-lg
      = f.label :Room, class: 'control-label'
      = f.label room.name, class: 'control-label'
      = f.hidden_field :room_id, value: room.id
    .form-group.form-group-lg
      = f.label :start, class: 'control-label'
      = f.time_select :start, class: 'form-control'
    .form-group.form-group-lg
      = f.label :finish, class: 'control-label'
      = f.time_select :finish, class: 'form-control'
    .form-group.form-group-lg
      = f.label :activity_type_id, class: 'control-label'
      = f.select(:activity_type_id, @activity_type.collect{|u| [u.name, u.id]}, prompt: 'Select')
    .form-group.form-group-lg
      = f.label :username, for: :username,  class: 'control-label'
      = f.text_field :username, class: 'form-control', placeholder: 'Name'
    .form-group.form-group-lg
      = f.label :secretword, class: 'control-label'
      = f.text_field :secretword,  class: 'form-control', placeholder: 'Secret Word'
    .form-group.form-group-lg
      = f.label :comment, class: 'control-label'
      = f.text_area :comment, class: 'form-control', placeholder: 'Description'
    .form-group.form-group-lg
      .pull-right
      = link_to 'Back', room_path(room.id), class: 'btn btn btn-default'
      = f.submit 'Save', class: 'btn btn-success'

app/views/reservations/_form_secretword.html.haml
.reservation-background{style: "background: url(/rooms/#{@reservation.room.image}) no-repeat top center fixed;"}
  .container
    = render 'layouts/alerts'
    .room-header
      .date= Time.now.strftime("%A %-d %B")
      = image_tag("/rooms/#{@reservation.room.nameplate_image}", alt: @reservation.room.name)
    = form_tag reservation_path(@reservation), method: :delete do
      .form-group.form-group-lg
        = label_tag :secretword, '', class: 'control-label'
        = text_field_tag :secretword, '',  class: 'form-control', placeholder: 'Secret Word'
      .form-group.form-group-lg
        .pull-right
          = submit_tag 'Send', class: 'btn btn-success'
    %br
    %br

app/views/reservations/edit.html.haml
%h1 Editing reservation
%container
  = render 'form'
  = link_to 'Show', @reservation, class: 'btn btn btn-default'
  \|
  = link_to 'Back', reservations_path, class: 'btn btn btn-default'

app/views/reservations/index.html.haml
%h1 Listing reservations
%container
  %table.table
    %tr
      %th Room
      %th Start
      %th Finish
      %th Activity type
      %th Username
      %th Secretword
      %th Comment
      %th Active
      %th
      %th
      %th

    - @reservations.each do |reservation|
      %tr
        %td= reservation.room.name
        %td= reservation.start
        %td= reservation.finish
        %td= reservation.activity_type.name
        %td= reservation.username
        %td= reservation.secretword
        %td= reservation.comment
        %td= reservation.active
        %td= link_to 'Show', reservation, class: 'btn btn btn-default btn-sm'
        %td= link_to 'Destroy', reservation, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn btn-default btn-sm'

  %br

  = link_to 'New Reservation', new_reservation_path, class: 'btn btn btn-default'

app/views/reservations/new.html.haml
- room_id = params[:reservation].blank? ? params[:room_id] : params[:reservation][:room_id]
- room = Room.find(room_id)
.reservation-background{style: "background: url(/rooms/#{room.image}) no-repeat bottom center fixed;"}
  .container
    .room-header
      .date= Time.now.strftime("%A %-d %B")
      = image_tag("/rooms/#{room.nameplate_image}", alt: room.name)
    = render 'form'

app/views/reservations/show.html.haml
%p#notice= notice

%p
  %b Room:
  = @reservation.room.name
%p
  %b Start:
  = @reservation.start
%p
  %b Finish:
  = @reservation.finish
%p
  %b Activity type:
  = @reservation.activity_type.name
%p
  %b Username:
  = @reservation.username
%p
  %b Secretword:
  = @reservation.secretword
%p
  %b Comment:
  = @reservation.comment
%p
  %b Active:
  = @reservation.active

= link_to 'Back', reservations_path, class: 'btn btn btn-default'

app/views/rooms/_form.html.haml
= form_for @room do |f|
  - if @room.errors.any?
    #error_explanation
      %h2= "#{pluralize(@room.errors.count, "error")} prohibited this room from being saved:"
      %ul
        - @room.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :image
    = f.text_field :image
  .actions
    = f.submit 'Save'

app/views/rooms/edit.html.haml
%h1 Editing room

= render 'form'

= link_to 'Show', @room
\|
= link_to 'Back', rooms_path

app/views/rooms/index.html.haml
.row
  - @rooms.each do |room|
    %a{:href => room_path(room)}
      - class_status = room.reservation_status == :busy ? 'room_booked' : ''
      .room_h.col-sm-6.col-md-4{class: class_status}
        .room
          .book
            %button.btn.btn-default.btn-lg.active{:type => "button"} Take meeting

          .status{class: room.reservation_status}

          %img{alt: room.name, src: "/rooms/#{room.preview_name}", width: "100%"}/

          .nameplate
            %img{alt: room.name, src: "/rooms/#{room.nameplate_image}"}/

          .people_quantity
            .glyphicon.glyphicon-user
            = room.people_quantity

app/views/rooms/new.html.haml
%h1 New room

= render 'form'

= link_to 'Back', rooms_path

app/views/rooms/show.html.haml
.room-background{style: "background: url(/rooms/#{@room.image}) no-repeat bottom center fixed;"}
  .container
    .room-header
      .date= Time.now.strftime("%A %-d %B")
      = image_tag("/rooms/#{@room.nameplate_image}", alt: @room.name)
    .shedule-wrapper
      %table
        - (9..20).each do |t|
          %tr
            %td.time= sprintf('%02d:00 - %02d:30', t, t)
            %td.line
          %tr
            %td.time= sprintf('%02d:30 - %02d:00', t, t + 1)
            %td.line
      .reservations{data: { new: new_reservation_path({room_id: @room.id})}}
        - start_of_day = Time.now.beginning_of_day + 9.hours
        - end_of_day = Time.now.beginning_of_day + 21.hours
        - @reservations.each do |reservation|
          - reservation.start = start_of_day if reservation.start <= start_of_day
          - reservation.start = end_of_day if reservation.start >= end_of_day
          - reservation.finish = start_of_day if reservation.finish <= start_of_day
          - reservation.finish = end_of_day if reservation.finish >= end_of_day
          - if reservation.start >= start_of_day && reservation.finish <= end_of_day && reservation.finish != reservation.start
            .reservation{style: "height: #{(reservation.finish.to_i - reservation.start.to_i) / 45}px;line-height: #{(reservation.finish.to_i - reservation.start.to_i) / 45}px; top: #{(reservation.start.to_i - Time.now.midnight.to_i) / 45 - 720}px;"}
              %span.username= reservation.username
              %span.comment.visible-md-block.visible-lg-block= reservation.comment
              %span.type.hidden-xs= reservation.activity_type.name
              %span.delete= link_to 'cancel reservation', reservation, method: 'delete', data: { confirm: 'Are you sure?' }
        - if Time.now >= start_of_day && Time.now <= end_of_day
          .current-time{style: "top: #{(Time.now.to_i - Time.now.midnight.to_i) / 45 - 720}px;"}